apiVersion: v1
kind: Secret

metadata:
  name: db-connection

data:
  url: cG9zdGdyZXNxbDovL3Bhc3NfaW5fb3duZXI6YWhMMEZpdjZzdUJsQGVwLXNvZnQtdW5pdC1hNTJvd203MS51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9wYXNzX2luP3NzbG1vZGU9cmVxdWlyZQ==

type: Opaque
