replicaCount: 4
image:
  repository: alexgms/pass-in
  pullPolicy: Always
  tag: a022f50
  port: 3333
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
startupProbe:
  httpGet:
    path: /health-check
    port: http
  initialDelaySeconds: 120
  failureThreshold: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /health-check
    port: http
  initialDelaySeconds: 120
  failureThreshold: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health-check
    port: http
  initialDelaySeconds: 120
  failureThreshold: 5
  periodSeconds: 10
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 8
  targetMemoryUtilizationPercentage: 75
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
